// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: MonitoringService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_system     MetricType = 0
	MetricType_cpu        MetricType = 1
	MetricType_disk       MetricType = 2
	MetricType_netTalkers MetricType = 3
	MetricType_netStats   MetricType = 4
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "system",
		1: "cpu",
		2: "disk",
		3: "netTalkers",
		4: "netStats",
	}
	MetricType_value = map[string]int32{
		"system":     0,
		"cpu":        1,
		"disk":       2,
		"netTalkers": 3,
		"netStats":   4,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_MonitoringService_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_MonitoringService_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_MonitoringService_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N    int64      `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	M    int64      `protobuf:"varint,2,opt,name=M,proto3" json:"M,omitempty"`
	Type MetricType `protobuf:"varint,3,opt,name=type,proto3,enum=monitoring.MetricType" json:"type,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MonitoringService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_MonitoringService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_MonitoringService_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Request) GetM() int64 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *Request) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_system
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MonitoringService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_MonitoringService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_MonitoringService_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_MonitoringService_proto protoreflect.FileDescriptor

var file_MonitoringService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x51, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x4e, 0x12, 0x0c,
	0x0a, 0x01, 0x4d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x4d, 0x12, 0x2a, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x1c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x49, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x69, 0x73,
	0x6b, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72,
	0x73, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x6e, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x10,
	0x04, 0x32, 0x4c, 0x0a, 0x11, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x12, 0x13, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e,
	0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MonitoringService_proto_rawDescOnce sync.Once
	file_MonitoringService_proto_rawDescData = file_MonitoringService_proto_rawDesc
)

func file_MonitoringService_proto_rawDescGZIP() []byte {
	file_MonitoringService_proto_rawDescOnce.Do(func() {
		file_MonitoringService_proto_rawDescData = protoimpl.X.CompressGZIP(file_MonitoringService_proto_rawDescData)
	})
	return file_MonitoringService_proto_rawDescData
}

var file_MonitoringService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MonitoringService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_MonitoringService_proto_goTypes = []interface{}{
	(MetricType)(0), // 0: monitoring.MetricType
	(*Request)(nil), // 1: monitoring.Request
	(*Result)(nil),  // 2: monitoring.Result
}
var file_MonitoringService_proto_depIdxs = []int32{
	0, // 0: monitoring.Request.type:type_name -> monitoring.MetricType
	1, // 1: monitoring.MonitoringService.GetMetrics:input_type -> monitoring.Request
	2, // 2: monitoring.MonitoringService.GetMetrics:output_type -> monitoring.Result
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_MonitoringService_proto_init() }
func file_MonitoringService_proto_init() {
	if File_MonitoringService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MonitoringService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MonitoringService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MonitoringService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MonitoringService_proto_goTypes,
		DependencyIndexes: file_MonitoringService_proto_depIdxs,
		EnumInfos:         file_MonitoringService_proto_enumTypes,
		MessageInfos:      file_MonitoringService_proto_msgTypes,
	}.Build()
	File_MonitoringService_proto = out.File
	file_MonitoringService_proto_rawDesc = nil
	file_MonitoringService_proto_goTypes = nil
	file_MonitoringService_proto_depIdxs = nil
}
